# Site settings
title: Dezdeepblue
description: Drips And Drops About Neucrack
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. https://dezdeepblue.com

permalink: /:categories/:title.html

# User settings
username: dezdeepblue
site_url: https://dezdeepblue.com
user_description: Embedded、Software、IOT、。。。
user_title: Creator
email: dezdeepblue@gmail.com
github_username:  dezdeepblue


# Google-analytics
google-analytics:
  id: 


